"""empty message

Revision ID: 878a81857491
Revises: eec5455f2608
Create Date: 2024-09-04 04:53:57.885041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878a81857491'
down_revision = 'eec5455f2608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
